### ISSUE TITLE
Improve documentation to mention the ScoreP requirement of --enable-shared

### ISSUE THREAD

**Issue by RobertHenschel** [score-p/scorep_jupyter_kernel_python#14]
I tried `pip install scorep-jupyter` and got the error that "ScoreP was not built with --enable-shared". If I am reading the documentation of ScoreP correctly, `--enable-shared` is not the default and needs to be enabled. So may this could be mentioned in the Installation section where it says now **For using the kernel you need a proper Score-P installation.**

**Comment by wrwilliams** [comment]
Switching the Score-P default to `--enable-shared` is planned for the 9.0 release, but @RobertHenschel is correct that the default is still static in 8.x.

**Comment by elwer** [comment]
thank you, fixed.
